#! /bin/bash
rm -rf ./out_files/100/*.out
rm -rf ./err_files/100/*.err

rm -rf ./out_files/200/*.out
rm -rf ./err_files/200/*.err

rm -rf ./out_files/300/*.out
rm -rf ./err_files/300/*.err

echo "MatrixSize;Nthreads;Time;SpmvTime;DotTime;LinCombTime;Residual;Error">result_omp_polus.csv

./make_dirs

make omp_polus
#for ((k = 0; k < 4; k += 1))
#do
for j in 100
do
for ((i = 1; i <= 32; i *= 2))
do
bsub < ./lsf_files/$j/$i.lsf
done
done
#done
