#! /bin/bash
rm -rf ./out_files/omp/1000/*.out
rm -rf ./err_files/omp/1000/*.err

rm -rf ./out_files/omp/4000/*.out
rm -rf ./err_files/omp/4000/*.err

rm -rf ./out_files/omp/6000/*.out
rm -rf ./err_files/omp/6000/*.err

echo "MulTime;Nthreads;MatrixSize;RunType">result_omp_polus_barriers.csv

./make_dirs
#./lsf_files/make_lsf

make omp_polus_barriers
for ((k = 0; k < 4; k += 1))
do
for j in 1000 6000
do
for ((i = 1; i <= 32; i *= 2))
do
bsub < ./lsf_files/$j/$i.lsf
done
done
done
