#! /bin/bash

for ((k = 0; k < 4; k += 1))
do
for ((j = 6000; j <= 6000; j += 3000))
do
for ((i = 1; i <= 32; i *= 2))
do
mpisubmit.pl -p $i --stdout ./out_files/$j/$i.out --stderr ./err_files/$j/$i.err ./prog -- $j
done
done
done
