#! /bin/bash
# echo "FullTime;ToRTime;GaussTime;Nthreads;MatrixSize;Residual;Error">result_omp_polus.csv
# ./make_dirs

# make
for ((j = 0; j < 4; j += 1))
do
for ((j = 1000; j <= 10000; j += 3000))
do
for ((i = 1; i <= 32; i *= 2))
do
mpisubmit.pl -p $i --stdout ./out_files/$j/$i.out --stderr ./err_files/$j/$i.err ./prog -- $j
done
done
done
