#! /bin/bash
echo "FullTime;ToRTime;GaussTime;Nthreads;MatrixSize;Residual;Error">result_mpi_polus.csv
./make_dirs

make
for ((k = 0; k < 4; k += 1))
do
for j in 1000 4000 6000
do
for ((i = 1; i <= 32; i *= 2))
do
mpisubmit.pl -p $i --stdout ./out_files/$j/$i.out --stderr ./err_files/$j/$i.err ./prog -- $j
done
done
done
