#! /bin/bash
echo "Time;Nthreads;RunType;Size">result_mpi_local.csv
# make
for ((k = 0; k < 4; k += 1))
do
for j in 1000 5000 10000
do
for ((i = 1; i <= 32; i *= 2))
do
mpiexec -n $i ./prog local $j
echo $i $j
done
done
done